In [1]:
import numpy as np
from scipy.spatial import distance

In [2]:
#1
N = 10
arr = np.arange(N)[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


In [3]:
#2
n = 10
diag_mat = np.diag(np.arange(n, -1, -1), k=0)
sum_diag_el = np.diagonal(diag_mat).sum()
print("Диагональная матрица:\n", diag_mat)
print("Сумма диагональных элементов матрицы:\n", sum_diag_el)

Диагональная матрица:
 [[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма диагональных элементов матрицы:
 55


In [4]:
#3
print( """4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3\n""")
X = np.array([[4,2,1],[1,3,0],[0,5,4]])
Y = np.array([4,12,-3])
print("x = ",round(np.linalg.solve(X,Y)[0],2))
print("y = ",round(np.linalg.solve(X,Y)[1],2))
print("z = ",round(np.linalg.solve(X,Y)[2],2))

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

x =  0.47
y =  3.84
z =  -5.56


In [5]:
#4
users_stats = np.array(
    [
        [0, 1, 2, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [0, 1, 2, 0, 0, 0]
    ], 
    np.int32
)

In [6]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [7]:
cos_simil = np.array([],'float64')
for i in users_stats:
    cos_simil = np.append(cos_simil,1 - distance.cosine(i,next_user_stats))
#cos_simil.argmax()+1
print("Самые похожие пользователи:")
for el in np.where(cos_simil == cos_simil.max())[0]+1:
    print(el)

Самые похожие пользователи:
1
10
